version: '3'

services:
  web:
    image: httpd:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/local/apache2/htdocs/public
      - ./config/httpd.conf:/usr/local/apache2/conf/httpd.conf
